spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/insurance
  application:
    name: insurance-management-service

server:
  port: 8084

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

management:
  tracing:
    sampling:
      probability: 1.0 #100% metrics will be published to zipkin server
