spring:
  application:
    name: identity-management-service
  config:
    import: "optional:configserver:http://localhost:8088"
  datasource:
    password: postgres
    url: jdbc:postgresql://localhost:2030/postgres
    username: postgres
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
    defer-datasource-initialization: true
    generate-ddl: true
  sql:
    init:
      mode: always

#server:
#  port: 9898
#
#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:8761/eureka/